### ISSUE TITLE
[Question] How can I configure the `permission_handler` in Flutter Module

### ISSUE THREAD

**Issue by cogivn** [Baseflow/flutter-permission-handler#1053]
Hi, 

Thank you for creating an awesome library. 
I am facing issues with configuring the `permission_handler` on a Flutter module. 

When I configured it according to the documentation and ran the Flutter module from Flutter, everything worked perfectly. However, when I exported the Flutter module as an AAR file and imported it into an existing app, no permission request occurred and I got an exception.
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null, null)
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      PermissionActions.request (package:permission_handler/permission_handler.dart:44:31)
                                                                                                    <asynchronous suspension>
                                                                                                    #4      _QrWidgetState._saveImageToGallery (package:socialclub/src/modules/events/presentation/widgets/reservation/qr_widget.dart:182:20)
                                                                                                    <asynchronous suspension>
 ```

Do I need to do a specific step to configure this library on my Flutter module? 
Thanks.

**Comment by cogivn** [comment]
I resolved the issue my way.
Thanks,

**Comment by parcool** [comment]
how you  resovled?
