### ISSUE TITLE
[Bug]: Request systemAlertWindow permission on Android TV

### ISSUE THREAD

**Issue by thorito** [Baseflow/flutter-permission-handler#1107]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. In app:
```
Future<bool> _checkPermission() async {
    final status = await Permission.systemAlertWindow.status;

    if (status.isDenied) {
      await Permission.systemAlertWindow.request();
    }

    return Permission.systemAlertWindow.status.isGranted;
  }
```
2. AndroidManifest.xml
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.POST_NOTIFICATION" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
```
3. I use flavors in the project.

When running it on mobile android it works correctly; but on android tv it throws exception

### Expected results

I would expect to have the same behavior on both platforms.

With other permissions such as camera, microphone,... it works correctly on both platforms

### Actual results

 E  Failed to handle method call
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:com.mypackage.example }
    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
    	at android.app.Activity.startActivityForResult(Activity.java:5207)
    	at android.app.Activity.startActivityForResult(Activity.java:5165)
    	at com.baseflow.permissionhandler.PermissionManager.executeIntent(PermissionManager.java:440)
    	at com.baseflow.permissionhandler.PermissionManager.requestPermissions(PermissionManager.java:274)
    	at com.baseflow.permissionhandler.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:66)
    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
 E  FATAL EXCEPTION: main
    Process: com.mypackage.example.dev, PID: 31375
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=211, result=0, data=null} to activity {com.mypackage.example.dev/com.mypackage.example.MainActivity}: java.lang.IllegalStateException: Reply already submitted
    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
    	at android.os.Handler.dispatchMessage(Handler.java:107)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    Caused by: java.lang.IllegalStateException: Reply already submitted
    	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
    	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda3.onSuccess(Unknown Source:2)
    	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
    	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
    	at android.app.Activity.dispatchActivityResult(Activity.java:8125)
    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
    	at android.os.Handler.dispatchMessage(Handler.java:107) 
    	at android.os.Looper.loop(Looper.java:214) 
    	at android.app.ActivityThread.main(ActivityThread.java:7356) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

permission_handler: ^10.4.3

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale es-ES)
    • Flutter version 3.10.5 on channel stable at /Users/thorito/development/flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/thorito/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/thorito/Documents/Curso Android Lollipop/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • KM3 (mobile)    • ATVKM301069FD5 • android-arm    • Android 10 (API 29)
    • macOS (desktop) • macos          • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome         • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by thorito** [comment]
any change?

**Comment by redanium** [comment]
I don't think it's a bug in the **package** , it's something related to the **OS**.

>From Android Marshmallow on, apps need to ask permission to the user for performing certain tasks, e.g. accessing contacts, or in our case: showing something on top of all other apps. Showing things on top, aka the overlay permission or more technically [SYSTEM_ALERT_WINDOW](https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW) permission, is considered a dangerous permission and requires special care. However, a lot of users got confused when their phone [started sayin](https://www.google.com/search?q=android+screen+overlay+detected)g “Screen overlay detected”, and big companies like Facebook started getting tons of support requests. So to mitigate the problem Google started (from Android 6.0.1) to grant this permission automatically if the app got installed through the Google Play store. 

> However, starting January 2019, they gradually started excluding apps from receiving this permission automatically. My little unpopular OnScreenClock app was one of the first apps to go down. In normal Android environment (non-TV), this does not pose a real problem as the user can still grant the permission themself. Unfortunately, on Android TV, there usually is no such user interface for granting the overlay permission (which requires a special user interface in contrast to “regular” permissions).

[
OnScreenClock permission fix
](https://mattiesworld.gotdns.org/weblog/onscreenclock-permission-fix/)

**Comment by TimHoogstrate** [comment]
Dear @thorito,

According to: [stackoverflow](https://stackoverflow.com/questions/66157941/intent-action-settings-action-manage-overlay-permission-not-working-for-androi/66178635#66178635)

 It is a known "bug" and won't be fixed as Google is [moving](https://www.androidpolice.com/2019/03/16/android-q-steps-up-the-fight-up-against-overlay-based-malware/) [away](https://www.androidpolice.com/2019/05/08/google-will-entirely-kill-the-overlay-permission-in-a-future-android-release/) from the OVERLAY permission.

Therefore, we will be closing this issue.

Kind regards,
