### ISSUE TITLE
[Reply already submitted][Bug]: Android crash : Reply already submitted

### ISSUE THREAD

**Issue by Passer-by** [Baseflow/flutter-permission-handler#1126]
### Please check the following before submitting a new issue.

- [x] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

Run permission_handler/example
Simultaneously tap ignoreBatteryOptimizations and notification.
Perform any action

### Expected results

App crash

### Actual results

The app is running normally.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

https://github.com/Baseflow/flutter-permission-handler/assets/58846244/1a8c66e2-3b19-4e33-a5d5-40f4ba7da284

</details>

### Version

master 10.4.3

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.19044.3324], locale zh-CN)
    • Flutter version 3.10.6 on channel stable at D:\code\flutter\SDK\flutter_windows_3.10.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\code\android\AndroidSDK
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: D:\code\android\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at D:\tools\Visual Studio\2022\Components
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.1)
    • Android Studio at D:\code\android\AS
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at D:\code\android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • V2055A (mobile)   • 343470231100DGT • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [版本 10.0.19044.3324]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 115.0.5790.173
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 115.0.1901.200

[!] Network resources
    X A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到


! Doctor found issues in 2 categories.
```

</details>

**Comment by Passer-by** [comment]
Log

D/CompatibilityChangeReporter(26737): Compat change id reported: 78294732; UID 12050; state: ENABLED
D/AndroidRuntime(26737): Shutting down VM
E/AndroidRuntime(26737): FATAL EXCEPTION: main
E/AndroidRuntime(26737): Process: com.baseflow.permissionhandler.example, PID: 26737
E/AndroidRuntime(26737): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=209, result=0, data=null} to activity {com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26737): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5742)
E/AndroidRuntime(26737): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5781)
E/AndroidRuntime(26737): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(26737): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(26737): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(26737): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(26737): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2550)
E/AndroidRuntime(26737): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26737): 	at android.os.Looper.loopOnce(Looper.java:223)
E/AndroidRuntime(26737): 	at android.os.Looper.loop(Looper.java:324)
E/AndroidRuntime(26737): 	at android.app.ActivityThread.main(ActivityThread.java:8540)
E/AndroidRuntime(26737): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26737): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
E/AndroidRuntime(26737): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
E/AndroidRuntime(26737): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26737): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(26737): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime(26737): 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
E/AndroidRuntime(26737): 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
E/AndroidRuntime(26737): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
E/AndroidRuntime(26737): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime(26737): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
E/AndroidRuntime(26737): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
E/AndroidRuntime(26737): 	at android.app.Activity.dispatchActivityResult(Activity.java:9085)
E/AndroidRuntime(26737): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5735)
E/AndroidRuntime(26737): 	... 13 more
I/flutter (26737): PermissionStatus.granted
I/flutter (26737): PermissionStatus.granted
D/_V_Process(26737): killProcess pid:26737
D/_V_Process(26737): java.lang.RuntimeException: here
D/_V_Process(26737): 	at android.os.Process.killProcess(Process.java:1324)
D/_V_Process(26737): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:204)
D/_V_Process(26737): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
D/_V_Process(26737): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
D/_V_Process(26737): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2311)
I/Process (26737): Sending signal. PID: 26737 SIG: 9
Lost connection to device.

**Comment by Passer-by** [comment]
Can add a synchronization lock, like https://github.com/Baseflow/flutter-permission-handler/pull/979

**Comment by Passer-by** [comment]
same issue https://github.com/Baseflow/flutter-permission-handler/issues/539

**Comment by Shik1266** [comment]
any news update?

**Comment by mhrzd** [comment]
version 10.4.1 works fine. I think it started since 10.4.2

**Comment by Shik1266** [comment]
> version 10.4.1 works fine. I think it started at 10.4.2
same issue in 10.4.1  😢

**Comment by JeroenWeener** [comment]
Could be the same cause as #761.

**Comment by Shik1266** [comment]
> Could be the same cause as #761.


I requested only one permission. 

log detail

io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:263)
com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult (PermissionManager.java:173)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:781)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:413)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult (FlutterActivityAndFragmentDelegate.java:820)
io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult (FlutterFragment.java:1172)
io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult (FlutterFragmentActivity.java:674)
android.app.Activity.dispatchRequestPermissionsResult (Activity.java:9124)

**Comment by JeroenWeener** [comment]
@Shik1266 can you provide us with the code you are running? I'd be interested to see which permission you are requesting and the way you request them.

**Comment by Shik1266** [comment]
@JeroenWeener 
i just requested notification permission once

code:
 await Permission.notification.request();

**Comment by JeroenWeener** [comment]
@Shik1266 this seems like a different issue than the one reported by the OP. I tested the behavior of the notification permission in the example app and did not encounter the issue you mention. I want to invite you to open a [new issue](https://github.com/Baseflow/flutter-permission-handler/issues/new/choose). Please include as much relevant information as possible, such as a minimal reproducible code sample and the output of `flutter doctor -v`.

**Comment by JeroenWeener** [comment]
Closing this issue as #1139 has been merged. Let us know if this issue has not been resolved using `permission_handler_android: 11.0.0`.

**Comment by fengmlo** [comment]
Tested on permission_handler: 11.0.1，not fixed.

**Comment by Passer-by** [comment]
Hi～ @JeroenWeener , In version 11.0.1, I tried testing the issue using the previous method, but the app did not crash. It's possible that there are other factors causing the "Reply already submitted" situation. Should I close this issue and ask others to open a new one?

**Comment by JeroenWeener** [comment]
Thank you @Passer-by, that would be appreciated.
