### ISSUE TITLE
[Bug]: App crashes with "RuntimeException android.app.ActivityThread in deliverResults" when trying to request BLUETOOTH_CONNECT permission

### ISSUE THREAD

**Issue by timalenustmf** [Baseflow/flutter-permission-handler#1153]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

not reproducible at the moment as it's an error that occurs at runtime and only on certain devices

### Expected results

App does not crash upon requesting a permission

### Actual results

We recently added this package in our app to handle our Android permissions better. 
We are noticing in our crash logs a fraction of our users is affected with an app crash as the result of the following exception:

`Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1452, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {coop.sommobilitat.carsharing/com.example.tmf_app.MainActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{655c252 11443:coop.sommobilitat.carsharing/u0a370} (pid=11443, uid=10370) requires android.permission.BLUETOOTH_CONNECT`

It only affects Android 12 and 13, which makes sense as the BLUETOOTH_CONNECT permission only exists there. We have not been able to reproduce the crash ourselves, eventhough we tried with Android 12 and 13 phones. From our crash logs we detect the affected devices are samsung/oppo/oneplus. 

### Code sample

<details><summary>This code sample does not reproduce the issue. This is how we use this package to request the necessary bluetooth permissions</summary>

```dart
Future<void> _requestPermission() async {
    if (Platform.instance.isAndroid) {
      var bluetoothScanPermission =
          (await Permission.bluetoothScan.request()).isGranted;
      var bluetoothConnectPermission =
          (await Permission.bluetoothConnect.request()).isGranted;
      var locationPermission = (await Permission.location.request()).isGranted;
      var permission = bluetoothScanPermission &&
          bluetoothConnectPermission &&
          locationPermission;
      if (permission) {
        _setState(BluetoothVehicleControllerState.readyToSearch);
      } else {
        _setState(BluetoothVehicleControllerState.missingPermission);
      }
    } else if (Platform.instance.isIOS) {
      var permission = (await Permission.bluetooth.request()).isGranted;
      if (permission) {
        _setState(BluetoothVehicleControllerState.readyToSearch);
      } else {
        _setState(BluetoothVehicleControllerState.missingPermission);
      }
    }
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 22.04.3 LTS 6.2.0-32-generic, locale en_US.UTF-8)
    • Flutter version 3.7.1 on channel stable at /home/timalenus/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (8 months ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/timalenus/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/127/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-32-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by JeroenWeener** [comment]
Hi @timalenustmf, thanks for providing this thorough bug report.

Could you provide us with the `AndroidManifest.xml` file you are using?

**Comment by timalenustmf** [comment]
> Hi @timalenustmf, thanks for providing this thorough bug report.
> 
> Could you provide us with the `AndroidManifest.xml` file you are using?

<details><summary>AndroidManifest.xml</summary>
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="coop.sommobilitat.carsharing"
    android:versionCode="40498465"
    android:versionName="23.07.2309131026" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="33" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <queries>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />

            <data android:mimeType="*/*" />
        </intent>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>

        <package android:name="com.facebook.katana" />
    </queries>

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />

    <application
        android:name="android.app.Application"
        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true" >
        <activity
            android:name="com.example.tmf_app.MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize" >

            <!--
           Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI.
            -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <meta-data
                android:name="flutter_deeplinking_enabled"
                android:value="true" />

            <intent-filter android:autoVerify="true" >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="@string/flavor_host"
                    android:scheme="https" />
                <data
                    android:host="@string/flavor_host"
                    android:scheme="tmf" />
                <data
                    android:host="payment-return"
                    android:scheme="@string/flavor_host" />
            </intent-filter>
        </activity>
        <!--
         Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java
        -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <provider
            android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
            android:authorities="coop.sommobilitat.carsharing.flutter_inappwebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

        <service
            android:name="com.baseflow.geolocator.GeolocatorLocationService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="location" />

        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver"
            android:exported="false" />
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
            android:exported="false" />
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />
            </intent-filter>
        </receiver>

        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />

        <activity
            android:name="be.appsup.firebase_dart_flutter.AuthActivity"
            android:excludeFromRecents="true"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="firebase.auth"
                    android:path="/"
                    android:scheme="genericidp" />
            </intent-filter>
        </activity>
        <activity
            android:name="be.appsup.firebase_dart_flutter.RecaptchaActivity"
            android:excludeFromRecents="true"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="firebase.auth"
                    android:path="/"
                    android:scheme="recaptcha" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name"
            android:theme="@style/com_facebook_activity_theme" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="cct.coop.sommobilitat.carsharing"
                    android:scheme="fbconnect" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:exported="true"
            android:theme="@style/AppTheme" />
        <activity
            android:name="com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity"
            android:exported="true"
            android:theme="@style/ThemeTransparent" />
        <activity
            android:name="com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.TrustedWebActivity"
            android:exported="true"
            android:theme="@style/ThemeTransparent" />
        <activity
            android:name="com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivitySingleInstance"
            android:exported="true"
            android:launchMode="singleInstance"
            android:theme="@style/ThemeTransparent" />
        <activity
            android:name="com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.TrustedWebActivitySingleInstance"
            android:exported="true"
            android:launchMode="singleInstance"
            android:theme="@style/ThemeTransparent" />

        <receiver
            android:name="com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ActionBroadcastReceiver"
            android:enabled="true"
            android:exported="false" />

        <meta-data
            android:name="io.flutter.embedded_views_preview"
            android:value="true" />

        <provider
            android:name="io.flutter.plugins.imagepicker.ImagePickerFileProvider"
            android:authorities="coop.sommobilitat.carsharing.flutter.image_provider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/flutter_image_picker_file_paths" />
        </provider>

        <activity
            android:name="io.flutter.plugins.urllauncher.WebViewActivity"
            android:exported="false"
            android:theme="@android:style/Theme.NoTitleBar.Fullscreen" />

        <uses-library
            android:name="androidx.window.extensions"
            android:required="false" />
        <uses-library
            android:name="androidx.window.sidecar"
            android:required="false" />

        <activity
            android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
            android:excludeFromRecents="true"
            android:exported="false"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
        <!--
            Service handling Google Sign-In user revocation. For apps that do not integrate with
            Google Sign-In, this service will never be started.
        -->
        <service
            android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
            android:exported="true"
            android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"
            android:visibleToInstantApps="true" />

        <activity android:name="com.facebook.CustomTabMainActivity" />
        <activity
            android:name="com.google.android.gms.common.api.GoogleApiActivity"
            android:exported="false"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <!--
         The initialization ContentProvider will call FacebookSdk.sdkInitialize automatically
         with the application context. This config is merged in with the host app's manifest,
         but there can only be one provider with the same authority activated at any given
         point; so if the end user has two or more different apps that use Facebook SDK, only the
         first one will be able to use the provider. To work around this problem, we use the
         following placeholder in the authority to identify each host application as if it was
         a completely different provider.
        -->
        <provider
            android:name="com.facebook.internal.FacebookInitProvider"
            android:authorities="coop.sommobilitat.carsharing.FacebookInitProvider"
            android:exported="false" />

        <receiver
            android:name="com.facebook.CurrentAccessTokenExpirationBroadcastReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.facebook.sdk.ACTION_CURRENT_ACCESS_TOKEN_CHANGED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.facebook.AuthenticationTokenManager$CurrentAuthenticationTokenChangedBroadcastReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.facebook.sdk.ACTION_CURRENT_AUTHENTICATION_TOKEN_CHANGED" />
            </intent-filter>
        </receiver>

        <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="coop.sommobilitat.carsharing.androidx-startup"
            android:exported="false" >
            <meta-data
                android:name="androidx.emoji2.text.EmojiCompatInitializer"
                android:value="androidx.startup" />
            <meta-data
                android:name="androidx.lifecycle.ProcessLifecycleInitializer"
                android:value="androidx.startup" />
        </provider>
        <provider
            android:name="io.sentry.android.core.SentryPerformanceProvider"
            android:authorities="coop.sommobilitat.carsharing.SentryPerformanceProvider"
            android:exported="false"
            android:initOrder="200" /> <!-- The activities will be merged into the manifest of the hosting app. -->
        <activity
            android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity"
            android:enabled="false"
            android:exported="false"
            android:launchMode="singleInstance"
            android:process=":playcore_missing_splits_activity"
            android:stateNotNeeded="true" />
        <activity
            android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
            android:exported="false"
            android:stateNotNeeded="true"
            android:theme="@style/Theme.PlayCore.Transparent" /> <!-- The services will be merged into the manifest of the hosting app. -->
        <service
            android:name="com.google.android.play.core.assetpacks.AssetPackExtractionService"
            android:enabled="false"
            android:exported="true" >
            <meta-data
                android:name="com.google.android.play.core.assetpacks.versionCode"
                android:value="11003" />
        </service>
        <service
            android:name="com.google.android.play.core.assetpacks.ExtractionForegroundService"
            android:enabled="false"
            android:exported="false" />
    </application>

</manifest>
```
</details>

**Comment by JeroenWeener** [comment]
@timalenustmf I am also having a hard time tracking down the problem. There are a few more things we can consider:
- Are you running a pure Flutter application? Or is Flutter embedded in a native Android app?
- Does your app's codebase include native Android code?
- Which dependencies are you using? (`pubspec.yaml` contents)

**Comment by timalenustmf** [comment]
> @timalenustmf I am also having a hard time tracking down the problem. There are a few more things we can consider:
> 
> * Are you running a pure Flutter application? Or is Flutter embedded in a native Android app?
**Pure Flutter application**
> * Does your app's codebase include native Android code?
**No**
> * Which dependencies are you using? (`pubspec.yaml` contents)

<details><summary>pubspec.yaml</summary>

```
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_html: ^2.2.1
  flutter_blue_plus: ^1.15.0
  url_launcher: ^6.0.0
  platform_info: ^3.1.0
  geolocator: ^8.2.1
  cached_network_image: ^3.2.3
  geocoding: ^2.0.2
  carousel_slider: ^4.0.0
  sentry_flutter: ^6.13.1
  tmf_sdk:
    path: ../tmf_sdk
  tmf_themes:
    path: ../tmf_themes
  tmf_flavors:
    path: ../tmf_flavors
  firebase_dart: ^1.1.0-dev.10
  firebase_dart_flutter: ^1.1.0-dev.8
  snapping_sheet: ^3.1.0
  connectivity_plus: ^2.2.1
  badges: ^2.0.1
  synchronized: ^3.0.0
  image_picker: ^0.8.3+2
  file_picker: ^4.0.0
  mask_input_formatter: ^0.0.3
  in_app_update: ^3.0.0
  app_settings: 4.1.6
  flutter_spinbox: ^0.8.0
  matomo: ^1.1.0
  move_to_background: ^1.0.2
  collection: ^1.15.0
  pointycastle: ^3.4.0
  intl: ^0.17.0
  flutter_inappwebview: '>=5.4.3+7 <5.5.0'
  pinput: ^2.2.22
  flutter_local_notifications: ^11.0.0
  form_builder_validators: ^8.3.0
  maps_launcher: ^2.0.1
  sticky_headers: ^0.3.0+2
  pedantic: ^1.11.1
  material_design_icons_flutter: 7.0.7296
  font_awesome_flutter: ^10.4.0
  universal_html: ^2.2.3
  permission_handler: ^11.0.0
```

</details>

Thanks for the effort in investigating this issue anyway. We're still observing the crashes in our crash logs. If it can help here is more information from what we see in our Sentry. This crash happened on a Samsung SM-A137F with Android 13. It seems the majority of the crashes are happening with Samsung devices. 

<details><summary>Runtime exception</summary>

`Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1452, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {coop.sommobilitat.carsharing/com.example.tmf_app.MainActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{dd65628 14525:coop.sommobilitat.carsharing/u0a325} (pid=14525, uid=10325) requires android.permission.BLUETOOTH_CONNECT
`
</details>

<details><summary>Stacktrace</summary>

```
android.app.ActivityThread in deliverResults at line 5994
android.app.ActivityThread in handleSendResult at line 6033
android.app.servertransaction.ActivityResultItem in execute at line 67
android.app.servertransaction.ActivityTransactionItem in execute at line 45
android.app.servertransaction.TransactionExecutor in executeCallbacks at line 135
android.app.servertransaction.TransactionExecutor in execute at line 95
android.app.ActivityThread$H in handleMessage at line 2574
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8757
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1067
```
</details>

<details><summary>SecurityException</summary>

`permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{dd65628 14525:coop.sommobilitat.carsharing/u0a325} (pid=14525, uid=10325) requires android.permission.BLUETOOTH_CONNECT`

</details>

<details><summary>Stacktrace</summary>

```
android.os.Parcel in createExceptionOrNull at line 3023
android.os.Parcel in createException at line 3007
android.os.Parcel in readException at line 2990
android.os.Parcel in readException at line 2932
android.app.IActivityTaskManager$Stub$Proxy in startActivity at line 2791
android.app.Instrumentation in execStartActivity at line 1801
android.app.Activity in startActivityForResult at line 5596
android.app.Activity in startActivityForResult at line 5554
com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin in lambda$onMethodCall$0 at line 4
com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin in f
com.boskokg.flutter_blue_plus.d in op at line 4
com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin in lambda$askPermission$5 at line 2
com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin in a
com.boskokg.flutter_blue_plus.a in op at line 6
com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin in onRequestPermissionsResult at line 3
io.flutter.embedding.engine.c$c in h at line 2
io.flutter.embedding.engine.c in onRequestPermissionsResult at line 3
io.flutter.embedding.android.e in x at line 9
io.flutter.embedding.android.d in onRequestPermissionsResult at line 2
android.app.Activity in dispatchRequestPermissionsResult at line 9124
android.app.Activity in dispatchActivityResult at line 8955
android.app.ActivityThread in deliverResults at line 5987
android.app.ActivityThread in handleSendResult at line 6033
android.app.servertransaction.ActivityResultItem in execute at line 67
android.app.servertransaction.ActivityTransactionItem in execute at line 45
android.app.servertransaction.TransactionExecutor in executeCallbacks at line 135
android.app.servertransaction.TransactionExecutor in execute at line 95
android.app.ActivityThread$H in handleMessage at line 2574
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8757
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1067
```

</details>

<details><summary>Remote Exception</summary>

```
RemoteException
Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1305)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1381)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:1025)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1942)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1815)
```

</details>

**Comment by timalenustmf** [comment]
Seems this is not an issue in this package, but rather in flutter_blue_plus that also requests the BLUETOOTH_CONNECT permission on Android. See also linked issue above.

**Comment by JeroenWeener** [comment]
@timalenustmf thanks for confirming. Hope it gets fixed!
