### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by jeonghoonkim** [Baseflow/flutter-permission-handler#119]
## 🐛 Bug Report

`PermissionHandler().checkPermissionStatus(PermissionGroup.camera)` not work on Android.

Failed to handle method call
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.baseflow.permissionhandler.PermissionHandlerPlugin.onMethodCall(PermissionHandlerPlugin.java:189)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:356)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
### Configuration
- permission_handler: 3.1.0

[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.5.4-hotfix.2
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at 
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.3

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

**Comment by jeonghoonkim** [comment]
I've resolved it just replace some code in PermissionHandlerPlugin.java
`@PermissionGroup final int permission = (int) call.arguments;`
by
`@PermissionGroup final int permission = Integer.parseInt(call.arguments.toString());`
