### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by elias-caceres-ueno** [Baseflow/flutter-permission-handler#1269]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Use native java code where the onActivityResult function is rewritten.
2. Have phone location disabled.
3. Request geolocation permission.
  In this step, you control whether or not you have permissions to access the geolocation. If you have the permission, the location is obtained using the Geolocator.getCurrentPosition() function
4. Accept or reject permissions.
  Here is the problem, and it is the following:

### Expected results

It is expected that the results of the onActivityResult can be handled properly and that the application does not close unexpectedly

### Actual results

The application quits unexpectedly and the following exception is thrown:

```console
E/AndroidRuntime(32173): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=17429, result=-1, data=Intent { (has extras) }} to activity {com.itti.ueno.dev/com.itti.ueno_app.ueno_app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32173): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5538)
E/AndroidRuntime(32173): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5577)
E/AndroidRuntime(32173): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(32173): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(32173): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(32173): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(32173): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
E/AndroidRuntime(32173): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32173): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(32173): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(32173): 	at android.app.ActivityThread.main(ActivityThread.java:8296)
E/AndroidRuntime(32173): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32173): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/AndroidRuntime(32173): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/AndroidRuntime(32173): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32173): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(32173): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime(32173): 	at com.itti.identity_verification.IdentityVerificationPlugin.onActivityResult(IdentityVerificationPlugin.java:179)
E/AndroidRuntime(32173): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
E/AndroidRuntime(32173): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime(32173): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:868)
E/AndroidRuntime(32173): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:1251)
E/AndroidRuntime(32173): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:691)
E/AndroidRuntime(32173): 	at android.app.Activity.dispatchActivityResult(Activity.java:8908)
E/AndroidRuntime(32173): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5531)
E/AndroidRuntime(32173): 	... 13 more
```

### Code sample

<details><summary>The flutter code sample</summary>

```dart
  Future<void> _getLocationData(
    GetLocationData event,
    Emitter<SelectAddressState> emit,
  ) async {
    try {
      final location = await Geolocator.getCurrentPosition();
      emit(state.copyWith(position: location));
    } catch (e) {
      emit(
        state.copyWith(
          position: Position(
              longitude: 0,
              latitude: 0,
              timestamp: DateTime.now(),
              accuracy: 0,
              altitude: 0,
              heading: 0,
              speed: 0,
              speedAccuracy: 0,
              altitudeAccuracy: 0,
              headingAccuracy: 0,
              floor: 0,
              isMocked: false),
        ),
      );
    }
  }
```
</details>

We have previously implemented a flutter plugin made in java that implements this code.
The `latestProcessor` is an instance of a class that I have implemented and `lastResult` is a instance of a `MethodChannel.Result` interface

Is there any problem with this code?
<details><summary>Native Java code</summary>

```java
  @Override
  public boolean onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
    String effectiveSource = "facetec";

    if (effectiveSource.equals(source) &&
            latestProcessor != null &&
            resultCode == RESULT_OK &&
            lastResult != null
    ) {
      try {
        String image = latestProcessor.getLastImage();
        boolean isSuccess = latestProcessor.isSuccess();
        int intents = latestProcessor.getRetryCount();

        ArrayList<String> result = new ArrayList<>();
        result.add(isSuccess ? "0" : "-1");
        result.add(image);
        result.add(String.valueOf(intents));

        System.out.println("---------------result---------------");
        System.out.println(result);
        System.out.println("------------------------------------");

        lastResult.success(result);

        lastResult = null;
      } catch (Exception error){
        error.printStackTrace();
        System.out.println("------------------------------------");
        System.out.println("error: " + error.getMessage());
        System.out.println("------------------------------------");
      }

      return true;
    } else {
      return false;
    }

  }
```
</details>

### Screenshots or video

The white screen is a loading screen displayed while the results of our flutter plugin are being processed

<details>
<summary>Screenshots or video demonstration</summary>

https://github.com/Baseflow/flutter-permission-handler/assets/156679360/86c8ad41-8bfc-4054-b9ba-fde02620b865

</details>

### Version

11.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.7, on Microsoft Windows [Versi¢n 10.0.22621.3007], locale es-PY)
    • Flutter version 3.13.7 on channel stable at C:\Users\elias\fvm\versions\3.13.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (4 months ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\elias\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\elias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[!] Connected device
    ! No devices available

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by elias-caceres-ueno** [comment]
Thank you so much, it was clear.

The error has been solved with the recommendation. 😁

**Comment by mvanbeusekom** [comment]
Great to hear, thank you for getting back to us. 

I will go ahead and close this issue.
