### ISSUE TITLE
[Bug]: Turning on and turning off external storage causes app crash.

### ISSUE THREAD

**Issue by sun-jiao** [Baseflow/flutter-permission-handler#1310]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. request external storage in code
2. in external storage settings page, turn it on and turn it off
3. go back to app

### Expected results

just a fallback that tells me the permission is not granted.

### Actual results

```
 E  FATAL EXCEPTION: main
 Process: ***, PID: 31283
 java.lang.RuntimeException: Unable to resume activity { ***/ ***.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity { ***/ ***.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5282)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5325)
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2630)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loopOnce(Looper.java:257)
 	at android.os.Looper.loop(Looper.java:368)
 	at android.app.ActivityThread.main(ActivityThread.java:8826)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
 Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity { ***/ ***.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5885)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5257)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5325) 
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64) 
 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185) 
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2630) 
 	at android.os.Handler.dispatchMessage(Handler.java:106) 
 	at android.os.Looper.loopOnce(Looper.java:257) 
 	at android.os.Looper.loop(Looper.java:368) 
 	at android.app.ActivityThread.main(ActivityThread.java:8826) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:142)
 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:774)
 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:422)
 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:857)
 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
 	at android.app.Activity.dispatchActivityResult(Activity.java:9116)
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5878)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5257) 
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5325) 
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64) 
 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185) 
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2630) 
 	at android.os.Handler.dispatchMessage(Handler.java:106) 
 	at android.os.Looper.loopOnce(Looper.java:257) 
 	at android.os.Looper.loop(Looper.java:368) 
 	at android.app.ActivityThread.main(ActivityThread.java:8826) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
```

### Code sample

https://github.com/sun-jiao/flut-renamer/blob/e661f8412616ff14ec9e776ced04886d8016de77/lib/main.dart#L155

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Arch Linux 6.8.5-arch1-1, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.2)
[✓] Proxy Configuration
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by TimHoogstrate** [comment]
Dear @sun-jiao,

This is a known issue for debug builds. That is because (when you go to settings) the flutter app basically gets detached. It should not happen in release builds. (you can test it yourself when you make a release build). I'll close this issue for now. Feel free to reopen when something similar pops up or is you have additional information. 

Kind regards,

**Comment by sun-jiao** [comment]
@TimHoogstrate No, it happens in release builds.

**Comment by AwaisQazii** [comment]
@sun-jiao  agreed

**Comment by lukeshomni** [comment]
@sun-jiao, I am facing a similar issue with release builds. Please let me know if you have found a solution for this. Your help would be much appreciated.

**Comment by AwaisQazii** [comment]
@lukeshomni  just use External Storage request method when user click on Camera/Gallery . Don't use in main method
