### ISSUE TITLE
[Question]: Failed to initialize decoder: c2.unisoc.avc.decoder

### ISSUE THREAD

**Issue by Harshu2032000** [Baseflow/flutter-permission-handler#1312]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

```dart
import 'dart:async';
import 'dart:io';
import 'package:audioplayers/audioplayers.dart';
import 'package:video_player/video_player.dart';
import 'package:chewie/chewie.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:flutter/material.dart';
import 'package:dfimages/screens/home/submit_api_hit.dart';

class UploadedMedia extends StatefulWidget {
  const UploadedMedia({Key? key}) : super(key: key);

  @override
  _UploadedMediaState createState() => _UploadedMediaState();
}

class _UploadedMediaState extends State<UploadedMedia> {
  late List<Map<String, dynamic>> deepfakes;
  late VideoPlayerController videoPlayerController;
  String mediaType = '';


  @override
  void initState() {
    super.initState();
    videoPlayerController = VideoPlayerController.file(
      File(''), // Initialize with an empty file path
    );

    videoPlayerController.initialize().then((_) {
      // Ensure the video is actually loaded before playing it.
      if (videoPlayerController.value.isInitialized) {
        videoPlayerController.pause();
      }
    });
  }

  @override
  void dispose() {
    videoPlayerController.dispose();
    super.dispose();
  }

  Future<List<Map<String, dynamic>>> _fetchDeepfakes() async {
    final databasePath = await getDatabasesPath();
    final String path = join(databasePath, 'deepfake_rest_api.db');
    final Database database = await openDatabase(path, version: 1);
    final q = await database.query('Media', where: 'status = ?', whereArgs: ['success']);
    final List<Map<String, dynamic>> qCopy = q.toList();
    final List<String> ids = [];
    for (var row in qCopy) {
      final id = row['job_id'].toString();
      ids.add(id);
    }
    // for (var id in ids) {
      // await _fetchAndUpdate(id);
    // }
    final db = await database.query('Media');
    return db;
  }

  Future<void> _fetchAndUpdate(String jobId) async {
    final databasePath = await getDatabasesPath();
    final String path = join(databasePath, 'deepfake_rest_api.db');
    final Database database = await openDatabase(path, version: 1);

    try {
      final _responseBody = await submitApiHit(jobId);

      await database.update(
        'Media',
        {
          'confidence': _responseBody!['confidence_percentage'],
          'result': _responseBody['result'],
          'date': _responseBody['date'],
          'gif': _responseBody['gif'],
          'description': _responseBody['description'] ?? 'Successfully Processed',
        },
        where: 'job_id = ?',
        whereArgs: [jobId],
      );

      final db = await database.query('Media');
      setState(() {
        deepfakes = db.toList();
      });
    } catch (e) {
      print(e);

    }
  }

  Widget _buildMediaWidget(String filePath) {
    final file = File(filePath);

    final fileExtension = filePath.split('.').last.toLowerCase();

    if (fileExtension == 'jpg' || fileExtension == 'jpeg' || fileExtension == 'png') {
      mediaType = 'Image';
      return Image.file(file);
    } else if (fileExtension == 'mp3' || fileExtension == 'wav') {
      mediaType = 'Audio';
      return AudioPlayerWidget(file: file);
    } else if (fileExtension == 'mp4' || fileExtension == 'webm') {
      mediaType = 'Video';

      videoPlayerController = VideoPlayerController.file(file);
      videoPlayerController.initialize().then((_) {
        if (videoPlayerController.value.isInitialized) {
          videoPlayerController.pause();
        }
      });
      final chewieController = ChewieController(
        videoPlayerController: videoPlayerController,
        autoPlay: true,
        looping: true,
      );
      return Container(
        width: 300,
        height: 200,
        child: Chewie(controller: chewieController),
      );
    } else {
      mediaType = "Invalid";
      return const Text('Invalid file type');
    }
  }

  Widget _buildRefreshButton(int jobId) {
    return IconButton(
      icon: Icon(Icons.refresh),
      onPressed: () {
        _fetchAndUpdate(jobId.toString());
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder<List<Map<String, dynamic>>>(
        future: _fetchDeepfakes(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.none) {
            return AlertDialog(
              title: const Text('No Connection'),
              content: const Text(
                  'Oops! There is no connection....... Check your Internet Connection '
                      'OR   contact us at contact.hyd@cdac.in '),
              actions: <Widget>[
                TextButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                  child: const Text('Close'),
                ),
              ],
            );
          } else if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          } else if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          } else if (snapshot.hasData) {
            deepfakes = snapshot.data!;
            return ListView.builder(
              itemCount: deepfakes.length,
              itemBuilder: (context, index) {
                final deepfake = deepfakes[index];
                final int jobId = deepfake['job_id'];
                dynamic confidenceValue = deepfake['confidence'];
                final String filePath = deepfake['file'];
                final Widget mediaWidget = _buildMediaWidget(filePath);

                return Container(
                  padding: EdgeInsets.all(8.0),
                  margin: EdgeInsets.symmetric(vertical: 4.0, horizontal: 3.0),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey),
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: ListTile(
                    title: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Job_ID: $jobId',
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Text(
                          'Result: ${deepfake['result']}',
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Text(
                          'Confidence: $confidenceValue',
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Text(
                          'Media Type: $mediaType',
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Container(
                          child: mediaWidget,
                        ),
                      ],
                    ),
                    trailing: _buildRefreshButton(deepfake['job_id']),
                  ),
                );
              },
            );
          } else {
            return const Center(child: Text('No data available'));
          }
        },
      ),
    );
  }
}

class AudioPlayerWidget extends StatefulWidget {
  final File file;

  AudioPlayerWidget({required this.file});

  @override
  _AudioPlayerWidgetState createState() => _AudioPlayerWidgetState();
}

class _AudioPlayerWidgetState extends State<AudioPlayerWidget> {
  late AudioPlayer audioPlayer;
  bool isPlaying = false;

  @override
  void initState() {
    super.initState();
    audioPlayer = AudioPlayer();
  }

  @override
  void dispose() {
    audioPlayer.dispose();
    super.dispose();
  }

  Future<void> _playAudio() async {
    await audioPlayer.play(UrlSource(widget.file.path));
    setState(() {
      isPlaying = true;
    });
  }

  Future<void> _pauseAudio() async {
    await audioPlayer.pause();
    setState(() {
      isPlaying = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    String fileName = widget.file.path.split('/').last;

    return Row(
      children: [
        IconButton(
          icon: Icon(isPlaying ? Icons.pause : Icons.play_arrow),
          onPressed: () {
            if (isPlaying) {
              _pauseAudio();
            } else {
              _playAudio();
            }
          },
        ),
        Text(fileName),
      ],
    );
  }
}
```

This is my code where i'm fetching data from API for audio video and images but after refreshing the page for3 or more times I get error as  MediaCodec error as below: 

```
W/MediaCodecRenderer(29714): Failed to initialize decoder: c2.unisoc.avc.decoder
W/MediaCodecRenderer(29714):   android.media.MediaCodec$CodecException: start failed
W/MediaCodecRenderer(29714):       at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(29714):       at android.media.MediaCodec.start(MediaCodec.java:2322)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
W/MediaCodecRenderer(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
W/MediaCodecRenderer(29714):       at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer(29714):       at android.os.Looper.loopOnce(Looper.java:201)
W/MediaCodecRenderer(29714):       at android.os.Looper.loop(Looper.java:288)
W/MediaCodecRenderer(29714):       at android.os.HandlerThread.run(HandlerThread.java:67)
I/DMCodecAdapterFactory(29714): Creating an asynchronous MediaCodec adapter for track type video
D/CCodec  (29714): allocate(c2.unisoc.avc.decoder)
E/MediaCodecVideoRenderer(29714): Video codec error
E/MediaCodecVideoRenderer(29714):   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.unisoc.avc.decoder, Format(1, null, null, video/avc, avc1.64001F, -1, null, [588, 1278, 30.01542], [-1, -1])
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/MediaCodecVideoRenderer(29714):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(29714):       at android.os.Looper.loopOnce(Looper.java:201)
E/MediaCodecVideoRenderer(29714):       at android.os.Looper.loop(Looper.java:288)
E/MediaCodecVideoRenderer(29714):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(29714):   Caused by: android.media.MediaCodec$CodecException: start failed
E/MediaCodecVideoRenderer(29714):       at android.media.MediaCodec.native_start(Native Method)
E/MediaCodecVideoRenderer(29714):       at android.media.MediaCodec.start(MediaCodec.java:2322)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
E/MediaCodecVideoRenderer(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
E/MediaCodecVideoRenderer(29714):       ... 11 more
I/CCodec  (29714): setting up 'default' as default (vendor) store
I/CCodec  (29714): Created component [c2.unisoc.avc.decoder]
D/CCodecConfig(29714): read media type: video/avc
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(29714): extent() != 1 for single value type: algo.buffers.pool-ids.values
E/ExoPlayerImplInternal(29714): Playback error
E/ExoPlayerImplInternal(29714):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [588, 1278, 30.01542], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
E/ExoPlayerImplInternal(29714):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(29714):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal(29714):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal(29714):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(29714):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.unisoc.avc.decoder, Format(1, null, null, video/avc, avc1.64001F, -1, null, [588, 1278, 30.01542], [-1, -1])
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/ExoPlayerImplInternal(29714):       ... 4 more
E/ExoPlayerImplInternal(29714):   Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(29714):       at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(29714):       at android.media.MediaCodec.start(MediaCodec.java:2322)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
E/ExoPlayerImplInternal(29714):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
E/ExoPlayerImplInternal(29714):       ... 11 more
```

### Version

ExoPlayer version 1.0.0  Flutter version  3.19.3    android 13   device Realme Narzo N53

**Comment by mvanbeusekom** [comment]
Hi @Harshu2032000,

Did you create this issue in the wrong repository? I fail to see how this is anywhere related to the Flutter `permission_handler` plugin.

I will go ahead and close this for now.
