### ISSUE TITLE
[Bug]: Null pointer exception on Android when android kills and restarts the activity

### ISSUE THREAD

**Issue by rorystephenson** [Baseflow/flutter-permission-handler#1360]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

In my case the path to trigger this is as follows, unsure if this affects only permissions which require being redirected to the settings menu or if it also affects permissions that are approved via popups:

1. `Permission.systemAlertWindow.request()`.
2. We are sent to settings.
3. Force Android to kill the app, an easy way to do this is by using the [Fill Memory](https://play.google.com/store/apps/details?id=com.overkaiser.libmemory&hl=en) app. You simply switch to that app, choose 'FILL UNTIL MEM LOW', then wait for Android to kill apps due to low memory.
4. Re-open the Flutter app, the crash will be triggered.

### Expected results

I'm not sure what is possible here, ideally `permission_handler` would be able to pick up where it left off or, at worst, re-request the permissions if needed. In any case it shouldn't throw a null pointer exception as this crashes the app.

### Actual results

It seems that Android kills the activity which clears the `requestResults` class variable, so when it then resumes the activity calling `put` leads to a null pointer exception [here](https://github.com/Baseflow/flutter-permission-handler/blob/9ea0affec3e62316a541d93b995ab6638a2fd078/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java#L142):

```console
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.e11wizards.app/com.e11wizards.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=211, result=0, data=null} to activity {com.e11wizards.app/com.e11wizards.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5288)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5331)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2640)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8832)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=211, result=0, data=null} to activity {com.e11wizards.app/com.e11wizards.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5891)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5263)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5331)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2640)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8832)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
       at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:1)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:9116)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5884)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5263)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5331)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2640)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8832)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

### Code sample

See steps to reproduce.

### Screenshots or video

Nothing much to see, the app just crashes.

### Version

11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-arm64, locale en-AU)
    • Flutter version 3.24.0 on channel stable at /Users/rorystephenson/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/rorystephenson/sdk/android
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/rorystephenson/sdk/android
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5556         • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by rorystephenson** [comment]
Possibly related issues: #968 #807

**Comment by diegofrata** [comment]
This is currently our most prevalent crash, which happens whenever we request permissions on a low-end device (usually Xiaomi) that require redirection to Android settings. These devices seem pretty committed to killing apps as soon as they go into background, I believe due to low memory. 

When returning from settings, the app is starting from cold so it has no recollection of requesting permissions and no callback to invoke, so in this case `onActivityResult` should just gracefully return. I don't think there's much else that can be done at this point. The PR I tagged was raised by someone else, but would likely fix the issue.

**Comment by rorystephenson** [comment]
That was a _really_ fast turnaround @mvanbeusekom, thanks a lot!
