### ISSUE TITLE
[Bug]: permission_handler_html uses `PermissionDescriptor`, which was recently removed from `package:web`

### ISSUE THREAD

**Issue by PiotrRogulski** [Baseflow/flutter-permission-handler#1363]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Add `permission_handler: 11.3.1` as a dependency (this pulls in `permission_handler_html` 0.1.3+1)
2. Add a dependency on `web: ^1.0.0`
3. Try to compile for the web (`flutter build web`)

### Expected results

The app builds without errors

### Actual results

Compilation fails – the package uses a `PermissionDescriptor` type, which was removed in the latest version of `package:web`, which the package claims to support. (The specific commit that removed it is https://github.com/dart-lang/web/commit/7604578eb538c471d438608673c037121d95dba5)

<details>
<summary>Compiler output</summary>

```
Compiling lib/main.dart for the Web...                          
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../.pub-cache/hosted/pub.dev/permission_handler_html-0.1.3+1/lib/web_delegate.dart:66:21:
Error: Method not found: 'PermissionDescriptor'.
        ?.query(web.PermissionDescriptor(name: webPermissionName))
                    ^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /home/piotr/fvm/versions/3.24.0/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/piotr/fvm/versions/3.24.0/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/home/piotr/fvm/versions/3.24.0/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/b8800d88be4866db1b15f8b954ab2573bba9960f/ --native-null-assertions --no-source-maps -o
  /home/piotr/repos/permission_example/.dart_tool/flutter_build/48eb26cc35ff0295e98c80dbb4ec1af9/app.dill --packages=.dart_tool/package_config.json --cfe-only
  /home/piotr/repos/permission_example/.dart_tool/flutter_build/48eb26cc35ff0295e98c80dbb4ec1af9/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:203:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:227:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             12.9s
Error: Failed to compile application for the Web.
```

</details>

### Code sample

Code archive:
[example.zip](https://github.com/user-attachments/files/16640506/example.zip)

Pubspec:
```
name: permission_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 11.3.1
  web: ^1.0.0

flutter:
  uses-material-design: true
```

(other files not changed from the default template)

### Version

0.1.3+1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Manjaro Linux 6.10.3-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.24.0 on channel stable at /home/piotr/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/piotr/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/piotr/.local/share/JetBrains/Toolbox/apps/android-studio-2/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12099254-b509.4)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-unstable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.2)
    • Android Studio at /home/piotr/.local/share/JetBrains/Toolbox/apps/android-studio-2
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12099254-b509.4)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.10.3-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6643.2 dev

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by zeefarm** [comment]
downgrade web to 0.5.1 solve the issue

**Comment by PiotrRogulski** [comment]
> downgrade web to 0.5.1 solve the issue

@zeefarm This doesn't really address the issue – I'm in the process of migrating a project to support `web ^1.0.0` and `permission_handler_html` is preventing this upgrade

**Comment by selvam920** [comment]
+1

**Comment by EDApps3** [comment]
+1

**Comment by scolnet** [comment]
Hello
@zeefarm The last version of share_plus requires now web 1.0.0
An upgrade would be great to be able to compile for the web 
Thans a lot

**Comment by bayunugroho2022** [comment]
i have same issue

**Comment by zhshimin** [comment]
+1

**Comment by hpoul** [comment]
fwiw, i've created a PR:

* https://github.com/Baseflow/flutter-permission-handler/pull/1364

feel free to test it:

```
dependency_overrides:
  web: ^1.0.0
  permission_handler_html:
    git:
      url: https://github.com/hpoul/flutter-permission-handler.git
      path: permission_handler_html
      ref: permissiondescriptor
```

**Comment by anversoft** [comment]
+1

**Comment by zeikman** [comment]
+1

**Comment by hnvn** [comment]
+1

**Comment by berkanaslan** [comment]
> fwiw, i've created a PR:
> 
> * [fix compile error with web 1.0 #1363 #1364](https://github.com/Baseflow/flutter-permission-handler/pull/1364)
> 
> feel free to test it:
> 
> ```
> dependency_overrides:
>   web: ^1.0.0
>   permission_handler_html:
>     git:
>       url: https://github.com/hpoul/flutter-permission-handler.git
>       path: permission_handler_html
>       ref: permissiondescriptor
> ```

Worked for me.

**Comment by EDApps3** [comment]
> > fwiw, i've created a PR:
> > 
> > * [fix compile error with web 1.0 #1363 #1364](https://github.com/Baseflow/flutter-permission-handler/pull/1364)
> > 
> > feel free to test it:
> > ```
> > dependency_overrides:
> >   web: ^1.0.0
> >   permission_handler_html:
> >     git:
> >       url: https://github.com/hpoul/flutter-permission-handler.git
> >       path: permission_handler_html
> >       ref: permissiondescriptor
> > ```
> 
> Worked for me. I'll be waiting for the merge to continue to use the package.

i'm getting 
/Users/eliedouaihy/src/flutter/bin/flutter --no-color pub get
Resolving dependencies...
Because permission_handler 11.3.1 depends on permission_handler_html ^0.1.1 and no versions of permission_handler match >11.3.1 <12.0.0, permission_handler ^11.3.1 requires permission_handler_html from hosted.
So, because flutter_tutorials_quizzes_2 depends on both permission_handler ^11.3.1 and permission_handler_html from git, version solving failed.
Process finished with exit code 1

**Comment by hpoul** [comment]
@EDApps3 are you sure you've added it to `dependency_overrides` and not `dependencies`?

**Comment by EDApps3** [comment]
> @EDApps3 are you sure you've added it to `dependency_overrides` and not `dependencies`?

it was added to dependencies , now it works thanks

**Comment by 5hirish** [comment]
+1 Facing similar issue 
```
.pub-cache/hosted/pub.dev/permission_handler_html-0.1.3+1/lib/web_delegate.dart:66:21: Error: Method not found: 'PermissionDescriptor'.
        ?.query(web.PermissionDescriptor(name: webPermissionName))
                    ^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

Unable to address it.
