### ISSUE TITLE
If Permission Status is disabled then how to redirect user for turn on location.

### ISSUE THREAD

**Issue by DhavalRKansara** [Baseflow/flutter-permission-handler#212]
Suppose I granted location permission for my application and now somehow the location of my phone is off. So in this scenario, I am getting  `PermissionStatus status` as `disabled`. So is there any way to redirect the user to turn on the location of the phone?

In this scenario (`PermissionStatus.disabled`) if I tried to ask for the location permission by the below code getting an exception.

- Code for Requesting Location when `PermissionStatus.disabled` : 
```
PermissionHandler().requestPermissions(
        [PermissionGroup.locationWhenInUse]).then(_onStatusRequested);
```

- Exception while trying to request location in the above scenario:
```
E/flutter (29031): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null)
E/flutter (29031): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (29031): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (29031): <asynchronous suspension>
E/flutter (29031): #2      PermissionHandler.requestPermissions (package:permission_handler/src/permission_handler.dart:85:30)
E/flutter (29031): <asynchronous suspension>
E/flutter (29031): #3      _ConnectToDoseminderUIState._askPermission (package:my_doses/src/modules/doseminder/setup/connect_to_doseminder/connect_to_doseminder_ui.dart:73:25)
E/flutter (29031): #4      _ConnectToDoseminderUIState.initState (package:my_doses/src/modules/doseminder/setup/connect_to_doseminder/connect_to_doseminder_ui.dart:45:5)
E/flutter (29031): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (29031): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (29031): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (29031): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (29031): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (29031): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (29031): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (29031): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (29031): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (29031): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (29031): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (29031): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (29031): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (29031): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (29031): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (29031): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (29031): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (29031): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (29031): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (29031): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (29031): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (29031): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (29031): #41     E
```

**Comment by mvanbeusekom** [comment]
@DhavalRKansara at the moment the plugin doesn't support turning on the location services when they are turned of. You can however redirect the user to the Application settings page using the `PermissionHandler().openAppSettings()` method.

The exception you receive, has to do with a different problem. In this case you are requesting permissions multiple times at the same time. The most common scenario where this happens, is when people call the method directly from their `Widget build(BuildContext context)` method. The build method can be called by the Flutter runtime multiple times in rapid succession. The best way to get around this is to create a statefull widget and get the location in the initState method.

Hope this answers your questions.
