### ISSUE TITLE
Reply already submitted crash on some device

### ISSUE THREAD

**Issue by uzumaki258** [Baseflow/flutter-permission-handler#261]
Hello
I use permission_handler: 4.4.0+hotfix.4 to access the gallery and camera. 
Here is my code:

`class _OptionView extends StatelessWidget {
  Future<bool> _checkPermission() async {
    PermissionStatus permission = await PermissionHandler()
        .checkPermissionStatus(PermissionGroup.storage);
    if (permission == PermissionStatus.granted) {
      return true;
    }

    Map<PermissionGroup, PermissionStatus> permissions =
        await PermissionHandler().requestPermissions([PermissionGroup.storage]);
    if (permissions.containsKey(PermissionGroup.storage)) {
      return permissions[PermissionGroup.storage] == PermissionStatus.granted;
    } else {
      return false;
    }
  }`

It's working in simulator and my device, but here is crash logged in firebase Crashlytics
![image](https://user-images.githubusercontent.com/26773292/78953477-25f2aa00-7b03-11ea-847a-d8cbf201f485.png)
`Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }} to activity {packageid/packageid.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5007)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
       at android.app.ActivityThread.access$1600(ActivityThread.java:231)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

`Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
       at c.d.a.d.a(d.java)
       at com.baseflow.permissionhandler.PermissionManager.lambda$requestPermissions$0(PermissionManager.java:167)
       at c.d.a.c.a(c.java)
       at com.baseflow.permissionhandler.PermissionManager$RequestPermissionsListener.onRequestPermissionsResult(PermissionManager.java:339)
       at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
       at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:126)
       at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
       at android.app.Activity.dispatchActivityResult(Activity.java:7169)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5003)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
       at android.app.ActivityThread.access$1600(ActivityThread.java:231)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Device occur crash :
Galaxy M30, Galaxy J3 Pop,  Galaxy S6 edge, Galaxy S8 Active ....

**Comment by uzumaki258** [comment]
Update to 5.0hotfix3 then this issue is gone. I will close it.
