### ISSUE TITLE
Caused by java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by kw2019ltd** [Baseflow/flutter-permission-handler#267]
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
       at com.baseflow.permissionhandler.-$$Lambda$jaw25RjOC1MkCtj_GrUMa_Xm3HE.onResult(lambda)
       at com.baseflow.permissionhandler.PermissionManager.lambda$requestPermissions$0$PermissionManager(PermissionManager.java:167)
       at com.baseflow.permissionhandler.-$$Lambda$PermissionManager$3imiXt8xVQwDRBMPJBMF7a3TfHw.onResult(lambda)
       at com.baseflow.permissionhandler.PermissionManager$RequestPermissionsListener.onRequestPermissionsResult(PermissionManager.java:339)
       at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
       at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:126)
       at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7507)
       at android.app.Activity.dispatchActivityResult(Activity.java:7333)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4552)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

![image](https://user-images.githubusercontent.com/47334522/79439239-3f04ca80-7fdd-11ea-96b0-335694dadfda.png)

**Comment by mvanbeusekom** [comment]
I am sorry but just dumping your stack trace here doesn't really help us solve your problem. If you would like us to spend our time to help you fix your problem, you should also spend some effort in making sure we have all the information you could give us. Beginning by filling out the issue template.

The one thing I can suggest is to have a look if you are not by accident requesting permissions a second time just before the first call has returned. A common pitfall is were people request permissions from their `build` method (which can fire in rapid succession and therefore call the `permission_handler` multiple times in a row).

**Comment by kw2019ltd** [comment]
i am requesting permission on initState method , for now i upgraded to the latest version.

will keep this issue open and monitor it.

**Comment by algodave** [comment]
Same issue here. PR #270 fixes it. I'm currently referencing that fork's branch in my project. @mvanbeusekom Please merge it when you get a chance, thanks!

**Comment by mvanbeusekom** [comment]
@kw2019ltd, @algodave, @sososdk I have just release version 5.0.0+hotfix.4 which includes the fixes from #270. 

@sososdk thanks a lot for the fix.
