### ISSUE TITLE
Cannot start app on Huawei. FATAL crash 

### ISSUE THREAD

**Issue by Oklahomawhore** [Baseflow/flutter-permission-handler#514]
## 🐛 Bug Report

Description: 
Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS

```
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 3.4s)
[   +1 ms] executing: /Users/wangshuzhu/Library/Android/sdk/platform-tools/adb -s 8UJDU19B23015969 shell echo -n b2ff87e143a4be437a38ab8f1cb347ec24b37985 > /data/local/tmp/sky.com.ulugames.app.sha1
[  +33 ms] executing: /Users/wangshuzhu/Library/Android/sdk/platform-tools/adb -s 8UJDU19B23015969 shell -x logcat -v time -t 1
[  +60 ms] --------- beginning of main
           04-13 11:22:22.426 I/ASSET_BASE_SERVICE( 2066): HwAssetBaseService::Init Enter
[   +6 ms] executing: /Users/wangshuzhu/Library/Android/sdk/platform-tools/adb -s 8UJDU19B23015969 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true com.ulugames.app/com.ulugames.app.MainActivity
[  +99 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.ulugames.app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+2561 ms] E/AndroidRuntime(10029): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(10029): Process: com.google.android.gms.persistent, PID: 10029
[        ] E/AndroidRuntime(10029): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10029):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
[        ] E/AndroidRuntime(10029):     at android.app.ActivityThread.access$2200(ActivityThread.java:298)
[        ] E/AndroidRuntime(10029):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
[        ] E/AndroidRuntime(10029):     at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/AndroidRuntime(10029):     at android.os.Looper.loop(Looper.java:213)
[        ] E/AndroidRuntime(10029):     at android.app.ActivityThread.main(ActivityThread.java:8201)
[        ] E/AndroidRuntime(10029):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(10029):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[        ] E/AndroidRuntime(10029):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
[        ] E/AndroidRuntime(10029): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10029):     at android.os.Parcel.createException(Parcel.java:2071)
[        ] E/AndroidRuntime(10029):     at android.os.Parcel.readException(Parcel.java:2039)
[        ] E/AndroidRuntime(10029):     at android.os.Parcel.readException(Parcel.java:1987)
[        ] E/AndroidRuntime(10029):     at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
[        ] E/AndroidRuntime(10029):     at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
[        ] E/AndroidRuntime(10029):     at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
[        ] E/AndroidRuntime(10029):     at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
[        ] E/AndroidRuntime(10029):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
[        ] E/AndroidRuntime(10029):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
[        ] E/AndroidRuntime(10029):     ... 8 more
[ +570 ms] E/AndroidRuntime(10036): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(10036): Process: com.google.android.gms.persistent, PID: 10036
[        ] E/AndroidRuntime(10036): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10036):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
[        ] E/AndroidRuntime(10036):     at android.app.ActivityThread.access$2200(ActivityThread.java:298)
[        ] E/AndroidRuntime(10036):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
[        ] E/AndroidRuntime(10036):     at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/AndroidRuntime(10036):     at android.os.Looper.loop(Looper.java:213)
[        ] E/AndroidRuntime(10036):     at android.app.ActivityThread.main(ActivityThread.java:8201)
[        ] E/AndroidRuntime(10036):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(10036):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[        ] E/AndroidRuntime(10036):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
[        ] E/AndroidRuntime(10036): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10036):     at android.os.Parcel.createException(Parcel.java:2071)
[        ] E/AndroidRuntime(10036):     at android.os.Parcel.readException(Parcel.java:2039)
[        ] E/AndroidRuntime(10036):     at android.os.Parcel.readException(Parcel.java:1987)
[        ] E/AndroidRuntime(10036):     at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
[        ] E/AndroidRuntime(10036):     at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
[        ] E/AndroidRuntime(10036):     at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
[        ] E/AndroidRuntime(10036):     at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
[        ] E/AndroidRuntime(10036):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
[        ] E/AndroidRuntime(10036):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
[        ] E/AndroidRuntime(10036):     ... 8 more
[        ] E/AndroidRuntime(10036): Caused by: android.os.RemoteException: Remote stack trace:
[        ] E/AndroidRuntime(10036):     at android.app.ContextImpl.enforce(libmapleframework.so:8178376)
[        ] E/AndroidRuntime(10036):     at android.app.ContextImpl.enforceCallingOrSelfPermission(libmapleframework.so:8176060)
[        ] E/AndroidRuntime(10036):     at com.android.server.pm.PackageManagerService.addOnPermissionsChangeListener(libmapleservices.so:4416508)
[        ] E/AndroidRuntime(10036):     at android.content.pm.IPackageManager$Stub.onTransact(libmapleframework.so:8117472)
[        ] E/AndroidRuntime(10036):     at com.android.server.pm.PackageManagerService.onTransact(libmapleservices.so:7440476)
[        ] E/AndroidRuntime(10036): 
[ +639 ms] E/AndroidRuntime(10040): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(10040): Process: com.google.android.gms.persistent, PID: 10040
[        ] E/AndroidRuntime(10040): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10040):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
[        ] E/AndroidRuntime(10040):     at android.app.ActivityThread.access$2200(ActivityThread.java:298)
[        ] E/AndroidRuntime(10040):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
[        ] E/AndroidRuntime(10040):     at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/AndroidRuntime(10040):     at android.os.Looper.loop(Looper.java:213)
[        ] E/AndroidRuntime(10040):     at android.app.ActivityThread.main(ActivityThread.java:8201)
[        ] E/AndroidRuntime(10040):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(10040):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[        ] E/AndroidRuntime(10040):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
[        ] E/AndroidRuntime(10040): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
[        ] E/AndroidRuntime(10040):     at android.os.Parcel.createException(Parcel.java:2071)
[        ] E/AndroidRuntime(10040):     at android.os.Parcel.readException(Parcel.java:2039)
[        ] E/AndroidRuntime(10040):     at android.os.Parcel.readException(Parcel.java:1987)
[        ] E/AndroidRuntime(10040):     at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
[        ] E/AndroidRuntime(10040):     at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
[        ] E/AndroidRuntime(10040):     at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
[        ] E/AndroidRuntime(10040):     at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
[        ] E/AndroidRuntime(10040):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
[        ] E/AndroidRuntime(10040):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
[        ] E/AndroidRuntime(10040):     ... 8 more

```

**Version:**  6.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
The `android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS` is a permission I couldn't find in the Android [manifest.permission](url) documentation. I do have found the following information: `This permission is one of the PackageManager of the platform framework level`. So it's weird that the permission is missing, you can try to add the permission in the AndroidManifest.xml, but I don't think that will solve the problem.  You can add the permission by typing ` <uses-permission android:name="android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS" />` in the AndroidManifest. You can try to update to the newest versions of the permission_handler (^7.1.0) and run the `flutter clean` followed by `flutter pub get` command, maybe it will solve the problem.

Another thing you can you try is running the code on an emulator, see if you get the same error?

Let me know if this helped or worked!

**Comment by Oklahomawhore** [comment]
This was caused by the Google Mobile Service installed on Huawei phone, once I removed the google service it's working fine.
