### ISSUE TITLE
Unable to detect current Android Activity., null, null

### ISSUE THREAD

**Issue by Ronadlo7** [Baseflow/flutter-permission-handler#552]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null, null)

**Comment by mvanbeusekom** [comment]
@Ronadlo7 could you please provide more details? 

1. Which version of the plugin are you using?
2. Output of the `flutter doctor -v` command?
3. Which method are you calling when you receive this error?

Most likely you are calling the `request` method which needs an activity to be able to show the permission dialog while your app is in the background. This is not allowed and the plugin will return the above exception.

**Comment by Ronadlo7** [comment]
Android depand on Flutter module ,flutter module depand on permission_handler: ^7.1.0, 
run Android App, then call method of   Permission.camera.request(), will appear ,
but run flutter module ,request this method is ok

**Comment by Ronadlo7** [comment]
Can you provide contact information？ provide example project?

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:67:9)
    <asynchronous suspension>
    #3      PermissionActions.request (package:permission_handler/permission_handler.dart:48:31)

**Comment by mvanbeusekom** [comment]
@Ronadlo7 the easiest would be to create a GitHub gist. But if this is difficult you can drop an email to dev(at)baseflow.com

**Comment by Ronadlo7** [comment]
ok，Sending a example project to your email of Sending to your mailbox

**Comment by Ronadlo7** [comment]
It has been sent successfully, have you received it?

**Comment by mvanbeusekom** [comment]
I received the file, downloading it and will have a look when I get some time.

**Comment by Ronadlo7** [comment]
How is it, has it reproduced?

**Comment by JDDV** [comment]
Hi @Ronadlo7, I've received the flutter project you're working on to help you with this issue.
As soon as I run your project I get directed to 'secondPage.dart', where there are 2 buttons.
The last button will call the checkCameraPermission method, but for me it didn't do anything.
I don't get the error you received, which was:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null, null)

But I did notice that the permission was not added in the AndroidManifest.xml, which is mandatory if you want to ask permission to the user.

In your project folder structure go to `Android > app > src > main > AndroidManifest.xml`

If you open the AndroidManifest you should add the following line: `<uses-permission android:name="android.permission.CAMERA"/>`.


Clear instruction on how to set the permission handler up can be found [here](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup).

A full list of all the permission that are available can be found [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/android/app/src/main/AndroidManifest.xml). This is the AndroidManifest.xml from the example app which is included in the permission_handler plugin, you can always check the example app to see how it works!

I hope this will help you, please let us know if the issue is solved or not.

**Comment by Ronadlo7** [comment]
I have add the permission in AndroidManifest.xml <uses-permission android:name="android.permission.CAMERA"/>.
but  still have this error

**Comment by Ronadlo7** [comment]
you run Android project ,not flutter module ,because if you run flutter module is ok, this error is run Android project

**Comment by JDDV** [comment]
I'm not entirely sure what you mean, but I've opened the project using the flutter_module_support folder, and I've opened the project using the Android folder. Both will run perfectly after adding the permission.

> you run Android project ,not flutter module ,because if you run flutter module is ok, this error is run Android project

Just to be sure it's not a weird flutter/package issue, have you ran `flutter clean` followed by the command `flutter pub get` and tried it again?

If it did not help, can you explain the steps you take from the beginning (opening the project, and how you run the project and test the project and so on)? Because I can't seem to reproduce the issue

**Comment by Ronadlo7** [comment]
you should be run AndroidToFlutter project ,not flutter_module_support folder ,

**Comment by Ronadlo7** [comment]
AndroidToFlutter is Android Project ,it depend on flutter_module_support, so you should be run AndroidToFlutter Project ,then it have the problem

**Comment by JDDV** [comment]
I can't open and run the NativeToFlutter app, it gives me an error saying 'File was loaded in the wrong encoding: 'UTF-8''. Reload in another encoding doesn't work either. In what language did you write the program, or what encoding did you use?

**Comment by Ronadlo7** [comment]
there are three java file ,you shoule be replece:
1.MainActivity.java
[MainActivity.java](https://github.com/Ronadlo7/ModuleDemo/blob/master/app/src/main/java/com/moke/module/MainActivity.java)

2.NativeActivity.java
[NativeActivity.java](https://github.com/Ronadlo7/ModuleDemo/blob/master/app/src/main/java/com/moke/module/NativeActivity.java)

3.TransitionActivity.java
[TransitionActivity.java](https://github.com/Ronadlo7/ModuleDemo/blob/master/app/src/main/java/com/moke/module/TransitionActivity.java)

**Comment by JDDV** [comment]
I can't open the links you send me, I get an 404 error saying the page does not exist.
Maybe your repo is private or something?

here's what I see when I click on those links:

![image](https://user-images.githubusercontent.com/47666699/118629181-a2a78b80-b7cd-11eb-8fe5-f69e7846e5ef.png)

**Comment by Ronadlo7** [comment]
now ,you can try again,

**Comment by JDDV** [comment]
I did manage to get the app running now, but I still don't get the same error down here you get when I click on one of those 2 buttons.
Are you sure you're starting the intent at the right way?

> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null, null)

This error shows that there is no Activity, so I think something goes wrong starting the intent where you ask for the permission.
I did see that you integrated the flutter module into your Android Project (I also used [method A](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar) to check if that would have solved the issue somehow. But I saw you used [method B](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code) which also worked the same way for me).
But have you also tried the next step, which is [Adding a Flutter screen to an Android app](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=default-activity-launch-java-tab#add-a-normal-flutter-screen)?

I saw you took step one, but I did not see calling the intents as mentioned in [step 2](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=default-activity-launch-java-tab#step-2-launch-flutteractivity). I think if you succesfully call an intent the way the tutorial shows that the permission_handler will have an activity and the permission request will work.
Let me know if it worked!

**Comment by Ronadlo7** [comment]
you also get this error? add FlutterView by TransitionActivity you can new Android Project by yourself ,then depend on  flutter module, See if there is such an error

**Comment by JDDV** [comment]
Hi @Ronadlo7, It took me a while because I had some troubles with my pc, but I figured out what the problem is.

In your method you do the following to start an intent:

```
    public void enterFlutter2(View view) {
        Intent intent = new Intent(this, TransitionActivity.class);
        Bundle bundle = new Bundle();
        bundle.putString("routeName", "/second");
        bundle.putString("arguments", "?{\"name\":\"" + "?????22" + "\"}");
        intent.putExtras(bundle);
        startActivityForResult(intent,100);
}
```

This way you do start an Intent, opening one of the screens you have made in Flutter, but the Activity will be null.

The way how you should start the activity is like this:

```
public void enterFlutter2(View view) {
        startActivity(
                FlutterActivity
                    .withNewEngine()
                    .initialRoute("/second")
                    .build(this));
    }
```

This is how you start a FlutterActivity, this way asking for the permission will work if you have added it to the AndroidManifest because the activity won't be null this way.
