### ISSUE TITLE
[Android 11] Null check operator used on a null value

### ISSUE THREAD

**Issue by MangoDevx** [Baseflow/flutter-permission-handler#579]
## 🐛 Bug Report

On Android 11, Samsung Galaxy S21, getting any granted or denied permission is causing an unhandled exception: `Null check operator used on a null value.` I created this project today, and installed the flutter SDK last night. I checked and the AndroidX, Jetifier, were both set to true and also checked the files in the Android dropdown on the readme.

Code I am running to test after getting this issue:
`Future _checkPermissions()async{
  await Permission.sms.isGranted;
}`

Full error:

> Syncing files to device SM G991U1...
E/flutter (23016): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (23016): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (23016): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (23016): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (23016): #3      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:67:30)
E/flutter (23016): #4      PermissionListActions.request (package:permission_handler/permission_handler.dart:107:16)
E/flutter (23016): #5      PermissionActions.request (package:permission_handler/permission_handler.dart:44:44)
E/flutter (23016): #6      _checkPermissions (package:nlp_app/main.dart:78:24)
E/flutter (23016): #7      main (package:nlp_app/main.dart:5:9)
E/flutter (23016): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (23016): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (23016): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23016): #11     _runZoned (dart:async/zone.dart:1789:10)
E/flutter (23016): #12     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (23016): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (23016): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (23016): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (23016): 
I/example.nlp_ap(23016): Thread[6,tid=23638,WaitingInMainSignalCatcherLoop,Thread*=0x782cad62c0,peer=0x134c0250,"Signal Catcher"]: reacting to signal 28
I/example.nlp_ap(23016): 
I/example.nlp_ap(23016): SIGSAVEPRF profile save

**Comment by MangoDevx** [comment]
I was not actually on stable branch, I was accidentally on beta.

**Comment by MangoDevx** [comment]
Closed due to thinking I was on the beta channel, I switched to the stable channel and I am receiving the same results.
