### ISSUE TITLE
[BUG] Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by PlugFox** [Baseflow/flutter-permission-handler#758]
#### Attempt to invoke virtual method '`android.content.pm.PackageManager android.app.Activity.getPackageManager()`' on a null object reference

Permissions:
+ camera
+ locationAlways
+ storage
+ requestInstallPackages

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {ru.ozon.magistral/dev.plugfox.magistral.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {ru.ozon.magistral/dev.plugfox.magistral.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 ```

```
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {ru.ozon.magistral/dev.plugfox.magistral.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5579)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4894)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
       at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:76)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8550)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5572)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4894)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Configuration

![image](https://user-images.githubusercontent.com/7805176/146357627-f4b3f640-dc19-4cb0-a8a7-e7983c3fc867.png)

`permission_handler: ^8.2.6`

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by PlugFox** [comment]
Crashlytics says bug at [this line](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java#L77)

**Comment by JDDV** [comment]
Hi @PlugFox, I commented on the other issue you reacted on too in issue #609.
I think it either has to do with Android 11 and closing the app when you request the `requestInstallPackages` permission (Only Android 11 shows that behavior). Or that the activity in the `PermissionManager` class isn't set yet, so an action like calling activity.getPackageManager() will result in a NullPointerException since the activity isn't set yet.

I would love to have as much information as possible so we can look into this problem further, can you send me some more information like a small code snippet where you ask for the permissions, the Android versions you tested your app on etc. ?
All the information you have will help!

**Comment by PlugFox** [comment]
Dart code with permissions:
https://gist.github.com/PlugFox/189b1c7d9340e58f919099dc785281f6

**Comment by PlugFox** [comment]
Devices:
![image](https://user-images.githubusercontent.com/7805176/146381919-75b69dc1-109f-4d7e-adca-7fef0d6b7989.png)
![image](https://user-images.githubusercontent.com/7805176/146381952-d1998df5-b856-49c6-ad74-0887ecf0510c.png)
![image](https://user-images.githubusercontent.com/7805176/146381984-756c6ec2-572c-41c8-af62-fc46096a7867.png)
![image](https://user-images.githubusercontent.com/7805176/146382017-0d05538b-2f5e-40e5-823f-b0c772a8ea00.png)
![image](https://user-images.githubusercontent.com/7805176/146382078-b2a1e608-e27c-4506-97a1-a3b4b3c90112.png)

**Comment by JDDV** [comment]
Hi @PlugFox, thanks for your reply. I've looked a bit more into this issue since other issues are also having this problem.
It turns out, as annoying as it is, this is the correct behavior for the `requestInstallPackages`. Since Android 11 Google implemented this behavior as a security feature. You can see the issuetracker from Google [here](https://issuetracker.google.com/issues/154157387?pli=1).

I've read on one of the issue trackers that they will change this behavior in a future build.

**Comment by JDDV** [comment]
I'll close this issue for now @PlugFox, if you have questions please feel free to let me know.

**Comment by tazik561** [comment]
> @JDDV App show native screen with "app instalation from other/unknown sources" request. And after that native window closed - crash occurred.
> 
> On my devices and emulators works perfectly.
> 
> Operating systems with crash: ![image](https://user-images.githubusercontent.com/7805176/146378838-ead76347-61c8-488c-813a-cf48c528a2df.png)
> 
> I fix it for myself with this crutches inside `PermissionManager.java`:
> 
> ![image](https://user-images.githubusercontent.com/7805176/146379517-4f28b5fd-5b97-4a2f-9930-68283abd871a.png) ![image](https://user-images.githubusercontent.com/7805176/146379604-5fa0b37a-5180-478c-b396-9aff0ed263f9.png)

packageManagerUnAvailable should be null or true or false? If we make it null, practically we ignore permission library , since the result is PermissionConstants.PERMISSION_STATUS_GRANTED
