### ISSUE TITLE
App crashed on requesting Permission.requestInstallPackages

### ISSUE THREAD

**Issue by ChivialK** [Baseflow/flutter-permission-handler#867]
## 🐛 Bug Report

```bash
I/OpenGLRenderer( 2459): Davey! duration=742109ms; Flags=1, FrameTimelineVsyncId=9374615, IntendedVsync=178512176053313, Vsync=178512176053313, InputEventId=756325558, HandleInputStart=178512176535608, AnimationStart=178512176537587, PerformTraversalsStart=178512176539046, DrawStart=178512193049151, FrameDeadline=178512209219979, FrameInterval=178512176526806, FrameStartTime=16666666, SyncQueued=178512194682745, SyncStart=178512194830922, IssueDrawCommandsStart=178512195001756, SwapBuffers=178512201672746, FrameCompleted=179254286000840, DequeueBufferDuration=4520313, QueueBufferDuration=2745105, GpuCompleted=179254286000840, SwapBuffersCompleted=178512205410142, DisplayPresentTime=0, 
D/CompatibilityChangeReporter( 2459): Compat change id reported: 78294732; UID 10313; state: DISABLED
D/AndroidRuntime( 2459): Shutting down VM
E/AndroidRuntime( 2459): FATAL EXCEPTION: main
E/AndroidRuntime( 2459): Process: com.hcchiang.playground, PID: 2459
E/AndroidRuntime( 2459): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=213, result=0, data=null} to activity {com.hcchiang.playground/com.hcchiang.playground.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2459): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5368)
E/AndroidRuntime( 2459): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
E/AndroidRuntime( 2459): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 2459): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 2459): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 2459): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 2459): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
E/AndroidRuntime( 2459): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2459): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 2459): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 2459): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime( 2459): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2459): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 2459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 2459): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2459): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime( 2459): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 2459): 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
E/AndroidRuntime( 2459): 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
E/AndroidRuntime( 2459): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 2459): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 2459): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:802)
E/AndroidRuntime( 2459): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 2459): 	at android.app.Activity.dispatchActivityResult(Activity.java:8388)
E/AndroidRuntime( 2459): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
E/AndroidRuntime( 2459): 	... 13 more
I/Process ( 2459): Sending signal. PID: 2459 SIG: 9
Lost connection to device.
```

### Expected behavior

Show the next permission request?

### Reproduction steps

Simply test all permission request on Android
```dart
Future<Map<Permission, PermissionStatus>> requestPermissions(
  Iterable<Permission> permissions,
) {
  if (permissions.isNotEmpty) {
    return permissions.toList().request();
  } else {
    return Future.value({});
  }
}
```
```dart
final _permissions = <Permission>[
    Permission.calendar,
    Permission.camera,
    Permission.contacts,
    Permission.location,
    Permission.locationAlways,
    Permission.locationWhenInUse,
    Permission.mediaLibrary,
    Permission.microphone,
    Permission.phone,
    Permission.photos,
    Permission.photosAddOnly,
    Permission.reminders,
    Permission.sensors,
    Permission.sms,
    Permission.speech,
    Permission.storage,
    Permission.ignoreBatteryOptimizations,
    Permission.notification,
    Permission.accessMediaLocation,
    Permission.activityRecognition,
    Permission.unknown,
    Permission.bluetooth,
    Permission.manageExternalStorage,
    Permission.systemAlertWindow,
    Permission.requestInstallPackages,
    Permission.appTrackingTransparency,
    Permission.criticalAlerts,
    Permission.accessNotificationPolicy,
    Permission.bluetoothScan,
    Permission.bluetoothAdvertise,
    Permission.bluetoothConnect,
  ];
```

When I press the back button on the Android Dialog when requesting `Permission.requestInstallPackages`, the error log appears and my app crashed.

### Configuration

compileSdkVersion 33

AndroidManifest.xml is almost the same like the one in the example, except package name.

Device: Pixel 4a

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Plugin Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ChivialK** [comment]
Same problem also found on Permission.ignoreBatteryOptimizations.

If I ask only one permission, it works. But if I ask multiple permissions, the app crashed.

```dart
// This one work
final _permissions = <Permission>[
    Permission.requestInstallPackages,
    Permission.ignoreBatteryOptimizations,
    Permission.accessNotificationPolicy,
];
// This did not work
final _permissions = <Permission>[
    Permission.requestInstallPackages,
    Permission.accessNotificationPolicy,
];
```

**Comment by mvanbeusekom** [comment]
Hi @ChivialK.

The problem is related to requesting multiple permissions at once. The `requestInstallPackages` and `ignoreBatteryOptimizations` work different from requesting most other permissions (these are requested by firing an Android intent, rather then using the `Activity.requestPermissions()` API).

The problem is that when the intent is fired the application is moved to the background causing other permission requests in progress to fail and crash because the result cannot be delivered (as the process cannot be found).

The solution is to request the `requestInstallPackages` and `ignoreBatteryOptimizations` permissions separate and individually. We are in the process of removing support for requesting multiple permissions at once as this is also not the way Apple and Android originally intended the feature to work.

**Comment by TKalo** [comment]
My team is calling manageExternalStorage and requestInstallPackages jointly, but calling them separately (or only calling requestInstallPackages) did not solve the issue. The android adb is throwing a runtime exception "Failure delivering result ResultInfo [...] to activity [...] NullPointerException: Attempt to invoke interface method [...] Map.put [...] on a null object reference"
