### ISSUE TITLE
Android ANR

### ISSUE THREAD

**Issue by onkarmonks** [Baseflow/flutter-permission-handler#883]
## 🐛 Bug Report

Facing an ANR on Android when the FLutter engine is initialized

We are seeing ANRs in firebase in PermissionHandlerPlugin.java class in the function startListening() at line 108.
Please find the log below

### Crash Log

main (runnable): tid=1 systid=21671 
       at com.baseflow.permissionhandler.PermissionHandlerPlugin.startListening(PermissionHandlerPlugin.java:108)
       at com.baseflow.permissionhandler.PermissionHandlerPlugin.onAttachedToEngine(PermissionHandlerPlugin.java:64)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:54)
       at java.lang.reflect.Method.invoke(Native method)
       at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:355)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:263)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:243)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:163)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:154)
       at io.flutter.embedding.engine.FlutterEngineGroup.createEngine(FlutterEngineGroup.java:182)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:151)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:120)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:99)
       at com.tatadigital.tcp.flutter_embed.EngineBinding.<init>(EngineBindings.kt:33)
       at com.tatadigital.tcp.TcpApplication.initiateEngines(TcpApplication.kt:112)
       at com.tatadigital.tcp.TcpApplication.onCreate(TcpApplication.kt:55)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
       at android.app.ActivityThread.access$1500(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Can we check this?

**Version:** 9.2.0

**Platform:** 
- [ ] :robot: Android

**Comment by JDDV** [comment]
Hi @onkarmonks, it's a bit hard to see from just a stack trace where the issue is coming from. An ANR is most if the times the issue due to the main thread, which is responsible for updating the UI, can't process input from the user, or isn't able to draw. There are multiple reasons why an ANR can happen, and multiple methods you can solve an ANR issue.
Maybe this [documentation](https://developer.android.com/topic/performance/vitals/anr) can help you out a bit better finding the issue.

Let me know if you worked it out, or if you're still facing the issue!

**Comment by JeroenWeener** [comment]
Closing this issue due to inactivity. Feel free to open a new issue if you are still experiencing this problem!
