### ISSUE TITLE
AssertionError when running on Android

### ISSUE THREAD

**Issue by dnkoulouris** [Baseflow/flutter-permission-handler#899]
## 🐛 Bug Report

When I ask for any permission, I get this error:

```

D/ZrHung.AppEyeUiProbe(15031): stop checker.
D/ZrHung.AppEyeUiProbe(15031): Current Activity:false
D/ZrHung.AppEyeUiProbe(15031): not watching, wait.
W/InputMethodManager(15031): startInputReason = 1
D/AndroidRuntime(15031): Shutting down VM
W/eleconsultatio(15031): Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/eleconsultatio(15031): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime(15031): FATAL EXCEPTION: main
E/AndroidRuntime(15031): Process: eu.bioassist.teleconsultation, PID: 15031
E/AndroidRuntime(15031): java.lang.AssertionError
E/AndroidRuntime(15031): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime(15031): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(15031): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(15031): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(15031): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:901)
E/AndroidRuntime(15031): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
E/AndroidRuntime(15031): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7951)
E/AndroidRuntime(15031): 	at android.app.Activity.dispatchActivityResult(Activity.java:7801)
E/AndroidRuntime(15031): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
E/AndroidRuntime(15031): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
E/AndroidRuntime(15031): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(15031): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(15031): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(15031): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
E/AndroidRuntime(15031): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(15031): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(15031): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(15031): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15031): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(15031): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
I/Process (15031): Sending signal. PID: 15031 SIG: 9
```

If I restart the app, permission is granted correctly. Android 9.

### Expected behavior
Should get the permission status.
### Reproduction steps  
Code snippet:  
```
bool hasCamera = false;
        bool hasMic = false;
        if (await Permission.camera.status.isGranted) {
          hasCamera = true;
        } else {
          PermissionStatus permissionStatus = await Permission.camera.request();
          if (permissionStatus.isGranted) {
            hasCamera = true;
          }
        }
        if (await Permission.microphone.status.isGranted) {
          hasMic = true;
        } else {
          PermissionStatus permissionStatus = await Permission.microphone.request();
          if (permissionStatus.isGranted) {
            hasMic = true;
          }
        }

```
### Configuration
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-GR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
    ! Error: denkoul-iPhone is not connected. Xcode will continue when denkoul-iPhone is connected. (code -13)
[✓] HTTP Host Availability
```

**Version:** 1.x

**Platform:**  Android

**Comment by adamsfru** [comment]
I had the same issue. Was using `FirebaseMessaging` and made the `.request()` via it's sdk instead.
https://firebase.flutter.dev/docs/messaging/permissions/#requesting-permissions

**Comment by dnkoulouris** [comment]
Found this [issue](https://github.com/firebase/flutterfire/issues/9430) in `firebase_messaging` package. Seems that the current issue is related to that package.  
As seen from comments, a temporary fix is to downgrade `firebase_messaging` to version 12.0.3.

**Comment by dnkoulouris** [comment]
Closed as this is probably related to another package and only occurs when both packages are in use. Temporary fix is in above comment.
