### ISSUE TITLE
Caused by java.lang.NullPointerException Attempt to invoke interface method 'void com.baseflow.permissionhandler.n$b.a(java.util.Map)' on a null object reference

### ISSUE THREAD

**Issue by Super-Bin** [Baseflow/flutter-permission-handler#968]
## 🐛 Bug Report

# Crashlytics - Stack trace
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=-1, data=Intent { (has extras) }} to activity {com.xxx/com.xxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.n$b.a(java.util.Map)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5567)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5606)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.n$b.a(java.util.Map)' on a null object reference
       at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:100)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
       at android.app.Activity.dispatchActivityResult(Activity.java:8472)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5560)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5606)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### Configuration

**Version:** 1.x
permission_handler: 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ x ] :robot: Android

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by tcf150** [comment]
i having the same issue as well when i using permission_handler_android: 10.2.1~
seem like is crash at
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void g.c.d.n$b.a(java.util.Map)' on a null object reference
       at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)

successCallback.onSuccess(results);  
````
the successCallback could be null, feel like similar issue with [#609](https://github.com/Baseflow/flutter-permission-handler/issues/609) which the `requestResults` might be null

**Comment by TimHoogstrate** [comment]
Dear @Super-Bin or @tcf150,

Can you explain a bit more about the steps to reproduce, or share an example project or some example code with us? It would help a lot investigating this issue.

Kind regards,
