### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=0, data=Intent {  }} to activity {com.xxx.xx/com.xxx.xxx.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by xang555** [Baseflow/flutter-permission-handler#973]
### Full logs error

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=0, data=Intent {  }} to activity {com.xxx.xx/com.xxx.xxx.MainActivity}}: java.lang.NullPointerException: Attempt to get length of null array
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4428)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4472)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

```
Caused by java.lang.NullPointerException: Attempt to get length of null array
       at com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult(PermissionManager.java:14)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:20)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:59)
       at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7533)
       at android.app.Activity.dispatchActivityResult(Activity.java:7384)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4424)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4472)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Version:** permission_handler: ^10.2.0

**Platform:** 
- Android 8.1.0

**Comment by JeroenWeener** [comment]
Hi @xang555, thank you for taking the time to file this bug report!

Could you provide us with a minimal reproducible code sample? That will allow us to quickly and reliably determine what is causing the issue.
